### ISSUE TITLE
iDeal Integration (online payment provider)

### ISSUE THREAD

**Issue by yksflip** [foodcoops/foodsoft#1008]
Feature request by [ardjan](https://forum.foodcoops.net/u/ardjan)
https://forum.foodcoops.net/t/feature-request-adding-ideal-payment-method-to-upstream-version/625

> already mentioned in another post is the iDeal integration for online payments with the Dutch banking system, also working in the Adam fork.

Already inside [foodcoops-adam](https://github.com/foodcoop-adam/foodsoft). 

Looks like there's already a plugin in foodcoop-adam: https://github.com/foodcoop-adam/foodsoft/commit/ef824eafb7359a4ba1aadb0322f8e525e37548b0

**Comment by yksflip** [comment]
ah great, the beta branch already uses `mollie-api-ruby`, some changes for the new api version are required, but it looks already very good. In foodsoft-adam you've added some attributes to the FinancialTransaction Model (like `payment_method, `payment_state` etc.) to track the transaction status. Do you think this this still the right place for this attributes?
I'm a bit confused by the `financial_transaction_type` and `financial_transaction_class` , do they offer a abstraction for this sort of thing? Or is it rather a thing foodcoops use to categorize their transactions?

**Comment by wvengen** [comment]
I think it can make sense to keep it with the FinancialTransaction model. If not, you could add an online payment model that mirrors the financial transactions which need to be tracked. (Btw, this tracking is important, because an online payment can succeed or fail, and Foodsoft may be notified later even after the user is offline again.)

The Financial transaction type and class are something introduced a while ago, and I think are mostly used by the Austrian foodcoops. The idea is that you can e.g. pay membership fee and show it separately in Foodsoft, or 'invest' and have it tracked but not used to pay member orders. I think that, just when entering a payment manually, you may need to specify the transaction type when doing an online payment (this is not implemented in the plugin yet, as the transaction types/classes were added later to Foodsoft). I think the financial transaction type/class system is in bad need of documentation (preferably with thelp of the people who actively use it).

If you allow specifying the financial transaction type as a query parameter too, then a deface override could be made to link from e.g. the dashboard to the payment page to pay the amount due (prefilled using the query parameters). This is currently also missing in the payment plugin, I think.

**Comment by yksflip** [comment]
thanks for your advise willem, I'll give it a shot :)
