### ISSUE TITLE
Add category/key/reason to FinancialTransactions

### ISSUE THREAD

**Issue by robwa** [foodcoops/foodsoft#170]
Add a table TransactionKey with <id,string> pairs and for FinancialTransaction a reference to that table.

This would allow summing up transactions over a certain period for a given key (e.g. summing up all sales for an inventory).

Find a German (sorry) discussion regarding some details in foodcoop-rostock/foodsoft#47.

**Comment by paroga** [comment]
I have a strong demand for this feature and like to try implementing it in the upstream source code.
I'd suggest adding:
* a page for managing the financial types (like order categories
* an entry in the settings page for configuring the financial type of the "automatic transactions"
* a dropdown select for the type when creating new financial transactions
* an additional column in the financial transactions of an order group

**Comment by wvengen** [comment]
@paroga please feel welcome to do so!

Some ideas:
* I see multiple types of "automatic transactions", e.g. settling an order, membership fee and online payment.
* To make Foodsoft easy to setup, I would like not to require configuring "automatic transactions" in the settings screen. Perhaps we could have system-transactions that are auto-created. E.g. using
  * Migration and database seed, and/or
  * Auto-create "automatic transaction type" whenever first entered.
* A radio select might be more usable, it requires one less click (see below). The long list transactions requires some thought, though, either showing them as a column, or only radio-ing frequently used transactions (and have the other in a select box, perhaps configurable as well). Something to think about, perhaps.
![types](https://cloud.githubusercontent.com/assets/503804/5774166/4b7d58d6-9d6b-11e4-9d48-f2e8a7e33556.png)
* (Something for the future, perhaps) it would at some point be nice to be able to use translated automatic transaction names, either on creation (based on the foodcoop default language) or on display (based on the user's language preference). This could be as simple as a boolean column indicating that the title field is an I18n name (or perhaps it's always the case for system columns).

And, naturally, please see these points as possible improvements, not expectations to live up to :)

**Comment by paroga** [comment]
thx for the additional ideas. collecting as many ideas as possible upfront makes total sense to me. let's see what I can do.
one additional point: in our food coop we dedicate specific amount for specific task. e.g. members make separate financial transactions for membership fee and money for received food. Since you can not buy goods for your payed membership fee, the money should not be recognised for the account balance. Additional a screen for checking to check the paid monthly membership fee would be a requirement for our foodsoft. Do you have a good idea to make this so generic that it makes sense in the original foodsoft and I do not need to maintain it in our fork?

**Comment by wvengen** [comment]
"Not recognising for the account balance" translates in my mind to creating a new transaction with negative amount. When a new user is created, a new financial transaction is also created of the negative membership fee. When he pays the fee, then the account is zero again.

Periodic membership fee would also be a wishlist feature, where a cronjob automatically charges membership fee for (active) members. What do you think?

**Comment by paroga** [comment]
in our food coop we have three account balances: registration fee, monthly membership fee, money for orders. when doing a bank transfer to the food coop every member marks the transaction withe the amounts for the different balances: e.g. I can say that when I transfer 100 EUR to the bank account of the food coop, 30 EUR are for registration, 30 EUR are for membership fees and the rest of 40 EUR is for personal orders. we need this strict operation, since paying the personal orders is not handled via the foodsoft.
the cron job must then only touch the "membership sub account balance".
beside that it should be possible for every user to see the sum of every "sub account balance".
In the meantime I had an idea about hierarchic types:
- Everything
  - Registration Fee
    - Bank Transfer For Registration Fee
    - Registration Refund
  - Membership
    - Bank Transfer For Membership Fees
    - Monthly Membership Fee
  - Personal Money
    - Bank Transfer For Personal Money
    - Internal Transfer
    - Invoice
    - Order

When configuring the types I can set a "sum flag" for the 3 second level types, which shows the sum of all sub types on a special overview page.

**Comment by paroga** [comment]
What do you think about hierarchic transaction types to create sums?

**Comment by paroga** [comment]
ping?

**Comment by paroga** [comment]
implemented in PR #407
