### ISSUE TITLE
English message "Invalid username or password" at login gives wrong advice as a login is only possible with email

### ISSUE THREAD

**Issue by marcopenhacking** [foodcoops/foodsoft#321]
I wasn't able to login with the username in https://foodsoft-translation.herokuapp.com (version 4.1.99).

So I think the English advice when wrong credentials are given should be updated to "Invalid e-mail or password".

**Comment by carottes** [comment]
Hi there,
Sorry, I dont understand your conversation before, because I have no clue about coding....
But same problem here. We are not able to login with the usernames nor e-mail-adress. When I switched the browser to Chrome, I could login at first. Today no browser works.
Also https://app.foodcoops.net/luzern/sessions seems doggy to me. Instead of "luzern" there occurs many different names, whenever I try to login again.
Problem also happens to linux laptop.
Do you have any idea?
Thanks so much

**Comment by wvengen** [comment]
Hi @carottes you're probably experiencing a different issue. It may be related to starting with the right url (luzern is the id of a certain foodcoop). You need to login to the correct instance.

Your foodcoop's technical support, or else foodcoops.net may be able to help to get to the right url, which depends on the foodcoop you're involved with.

**Comment by carottes** [comment]
All right. Thank you!
