### ISSUE TITLE
Import Database error

### ISSUE THREAD

**Issue by wedel** [foodcoops/foodsoft#374]
Das importieren eines externen Anbieters funktioniert nicht. Unter dem Menüpunkt Suppliers kann man rechts auf 'Import supplier from external Database'. Es öffnet sich die 'shared_suppliers' Seite mit einem Foodsoft Fehler!

Wie kann man eine Datenbank mit Artikeln, am besten von einem Anbieter importieren?

Using Foodsoft 4.4.0, runnig on my own server.

**Comment by wvengen** [comment]
Hi, thanks for your issue. Could you please describe more about your installation? Which version of Foodsoft are you using, are you running your own copy as a foodcoop or use one at foodcoops.net? If you run your own instance, you need to install sharedlists (e.g. from [here](https://github.com/foodcoop-adam/sharedlists/)) for the shared suppliers database.

**Comment by wvengen** [comment]
Ah, I see you've updated the description, thanks (adding a comment would have sent me a notification).
The external database (sharedlists) feature is meant to allow foodcoops to subscribe to suppliers shared by all foodcoops on the server. This is, for example, used at foodcoops.net for some organic wholesale retailers, which have thousands of products. A foodcoop then selects just the products it wants to order.

I don't think it makes sense to have this button when sharedlists isn't setup. Fixed in 58df186a2ad740337cb405caa9d603fe5212aff1.

See also
http://foodsoft.51229.x6.nabble.com/How-to-set-up-a-shared-supplier-shared-list-td1148.html#a1149
http://foodsoft.51229.x6.nabble.com/Re-updating-articles-from-csv-was-Re-Everyone-on-gmail-is-receiving-the-messages-but-no-one-else-is-td923.html#a942

**Comment by wvengen** [comment]
I hope this answers your question, and solves the usability problem. I'll close the issue now, please feel free to reopen if it's still unclear to you.
