### ISSUE TITLE
Implement "stock orders"

### ISSUE THREAD

**Issue by paroga** [foodcoops/foodsoft#389]
We do not use the stock features of the foodsoft, but we sometime need to add additional items for our stock to orders. At the moment we use an additional order_group for that purpose. That works quite well, but having shared credentials is not a good solution. So I thought about the following feature:
People who can create/modify order get an additional button in the context of the order where they can select articles for the stock (with the same UI like for every other group_order). Internal I could reuse the existing group_order, but have the specials ordergroup_id "0", which marks the "stock order".
What do you think about it?

**Comment by wvengen** [comment]
Vokomokum uses a special account as well for that.
I like the idea of being able to order for special accounts like stock and extra-for-when-we-spill-a-bit.
The simplest approach would be to allow the "sudo" button (member admin page) for the stock member for all with the orders permission. Nicer would be to allow members with the orders permission to order as (a limited set) of other members. Somehow I would want to have the stock member as a real member, so that it appears in lists as well at many places (and you get the financial transaction view as well).
In the group_orders view one might be able to switch between allowed members (with a clear signal as which user you're currently ordering). Need to think more about the UI though.
What do you think about keeping a member for stock (and potentially other uses like kitchen/bar/...)?

**Comment by paroga** [comment]
My idea was that that we have a special (not existing) "ordergroup" where everybody with the orders permission is member. People with the required permission have a button (like the "change order") where they can open the order. Internal the stock order is stored like a normal `group_order`, where the `ordergroup_id` is _NULL_. So we also see "who" placed the stock order via the `updated_*` fields in the `group_order` table.
Balancing should be handled in the same way like if the supplier delivered more than ordered, which means that the "stock order" is just ignored there.

**Comment by paroga** [comment]
Implemented in 9c4d9d5c2082dfbd807159c3f60ec0471bf6ec51

**Comment by mjavurek** [comment]
I like this feature and we often use it in our FC. During balancing, the stock orders should be excluded from the total amount of the order, because no existing ordergroup will be charged for it: When we add both order and stock delivery to the invoice, the stock order is  considered twice: once in the order and a second time by the stock delivery. As a result, a loss for the foodcoop is displayed with the amount of the stock order.
