### ISSUE TITLE
small suggestion for make /messages fiel more forum

### ISSUE THREAD

**Issue by gettingfooddone** [foodcoops/foodsoft#394]
Hi,

i hope this time i haven't overlooked anything again that is in place already :grimacing:

i'm aware of #368. Since to me it looks like still some way to go would it be a meantime solution for these small chances?
 - [ ] mark messages as read and unbold them in messages overview once they have received a click
 - [x] introduce sort-of-threads by indenting answers to initial messages

What do u say, would that be fairly easy to realize? Cheers.

**Comment by wvengen** [comment]
Nice ideas! And no, they are currently not present.

Marking messages as read would need the introduction of a new join model between user and message - since a message can be read for one user but not for another.

We could introduce a threads mode, where threads are those message where (I think) `reply_to` is unset. I'm afraid it would need a recursive query to find the _last_ message of a thread :(

A gem like [mailboxer](https://github.com/mailboxer/mailboxer) would make this a lot easier, optionally with something like [rails-messaging](https://github.com/frodefi/rails-messaging).
