### ISSUE TITLE
Set account balance to 0 for all

### ISSUE THREAD

**Issue by Schaussi** [foodcoops/foodsoft#438]
Example:
- User A has an account balance of -7
- User B has -10

Both users pay afterwards, the new account value is 0.
The administrator now has to enter the exact values they paid, as a new transaction.
For our use case, it would be great to have a button which inserts an appropriate transaction for every user so everyone's account value is at 0 again.
I know this might seem weird, but would be a convenient feature in some cases, e.g. when the administrator exactly knows everyone has paid the right sum.

**Comment by wvengen** [comment]
I've seen cooperatives wanting to use this feature too. In these cases, it happened that the administration wasn't setup quite that well (yet). It's a lot safer to still enter all the amounts paid, so that any errors are caught.

Having said this, I can see the need for this option. Perhaps would be a useful option in the batch financial transaction screen.
