### ISSUE TITLE
Katuma, possible collaboration? FOSDEM?

### ISSUE THREAD

**Issue by enricostano** [foodcoops/foodsoft#456]
Hi, this is not a real issue... sorry if this channel is considerated inappropriate for this kind of stuff.

I've just sent an email to `foodsoft (ät) foodcoops.net`, but since the FOSDEM 2017 is near I wanted to gather some attention. :/

Here is the content of the email:

Hi!

I'm Enrico, member of Coopdevs which develops free software for social and communitary economy. One of our projects is Katuma, a platform to foster consumer groups and the information flow between them and the local producers. Our aim is not only to write the software but to offer a complete SaaS experience around it.

I've been looking at FoodSoft code base and we share some part of the stack, Rails for instance. Stack apart I think that maybe we should talk since I guess we overlap at some point and would be great to find some kind of collaboration.

Some of us will be at FOSDEM 2017 this weekend, is there any chance that some people from your organization will be there too? Would be a great occasion to meet IMHO. If not maybe we can set a video call starting from next monday, we're based in Barcelona (Spain).

I'll create an issue in the GitHub repo too to gather some attention from the contributors, sorry for the SPAM.

Here you can find more info about us and about our projects:

http://coopdevs.org (CAST/CAT only for now sorry)
http://community.coopdevs.org (our forum)
http://katuma.org

https://github.com/coopdevs/katuma
https://github.com/coopdevs/katuma-web

I hope we can talk and look for lines of collaboration.

Bye,

Enrico

@enricostano

**Comment by wvengen** [comment]
Hi, thanks for getting in touch! It would be really nice to look at this. I'm afraid I'm not making it to FOSDEM, but if anyone else is, that would be a great opportunity.
Others to get in touch with would be https://github.com/ouisharelabs/food-dashboard and https://openfoodnetwork.org/

**Comment by enricostano** [comment]
@wvengen nice! Well let's plan a meeting then trying to talk all together. What about next week? Do you have contacts in those other projects?

**Comment by wvengen** [comment]
@elf-pavlik @Selmo-OFN @paroga anyone interested in a (food)coop-infrastructure get-together at FOSDEM with @enricostano (et al.)?

**Comment by enricostano** [comment]
cc/ @sauloperez

**Comment by paroga** [comment]
we are in the process of setting up a legal entity for the austrian foodcoops and have a meeting about it next weekend (where i'll attend). so no FOSDEM for me either. our goal is that this new entity will also take care about all necessary IT-stuff required for the foodcoops in austria, including austria-wide foodsoft-hosting (and a lot more). so i think that we do already our own thing. :-/

but i would be highly interested in sharing experiences and ideas.

i had only a short look over the codebase of katuma and didn't try it myself, but don't see a big difference to the existing foodsoft? can you give a little information about what's different between the two projects and why you started a new project?

**Comment by djodjoni** [comment]
Hi @enricostano I am part of Linked.Farm. We seem to share similar values, that is bringing consumers and producers closer together. We don't share stacks as we are stack-less :)  our goal apart from enhancing consumer producer collaboration and short supply chain, is to enhance transparency around food production and supply chain and enable anybody willing to take part in it to do that easily. We want to achieve this by generating Linked Open Food Data and software enablers enhancing interoperability between different SW solutions or plugging-in to already existing e-shopping solutions.
You can find the initial write-up of the idea here https://github.com/openthings-cc/FarmFood-Interoperability

So I think it will be nice to meet I will be there probably both days in the afternoon. I believe @cristianvasquez, also co-founder of this project, will be there as well.
my number is: +32486174776
btw a good place to look for collaboration is this https://github.com/ouisharelabs/food-dashboard/issues/1
@elf-pavlik  If you can make it will be nice to meet again :)

**Comment by enricostano** [comment]
Cool! We started coding a MVP just to have a prototype to play with while discussing with the local community of food coops and producers (co-design, agile, etc.). But we're open to join development on similar stacks if there is room for improvement for everybody.

The important think for us is to provide a reliable service (as SaaS), not only developing the software. We're planning to create a workers cooperative to build, maintain and provide that.

> Linked Open Food Data and software enablers enhancing interoperability between different SW solutions

💯 this is super interesting!

I'll be in Bruxelles starting from friday afternoon until sunday. My phone number is +34675465104 I'll hopefully be available on Telegram or Whatsapp.

**Comment by elf-pavlik** [comment]
Hola o/

Thank you for mention @wvengen :bowing_man: 

I lost momentum a bit on food-dashboard after moving to Mexico City, so also sadly no FOSDEM for me :(

At the same time, I prepare to deploy an instance of https://openfoodnetwork.org/ here and already started discussing consumer cooperatives with friends who work on https://vientos.coop

I still dedicate part of my attention to https://valueflo.ws/ and lately started engaging with http://coopdata.org/standards/

Happy to help with organizing online call with everyone interested in syncing-up in those topics. I guess we could do that sometimes after FOSDEM?

**Comment by myriamboure** [comment]
Hi everyone! I'm part of the Open Food Network project, which is also based on Rails. @enricostano we are providing OFN in France as Saas service, and for your info in UK they have adopted the platform coop model (in France we chose more the WIkipedia type of Common)
Also @djodjoni  I have initiated a project of food platform cooperation in France called Data Food Consortium (website to come soon) in order to build a common meta-ontology and semantic web type food data, I think it's connected to the LDP discussion. I'm not technical myself, just gathering the ecosystem to enable producers to share their data with whatever application. There are 5 French food platforms around the table (The Food Assembly, Open Food France, Panier Local, Cagette.net and Ekylibre), we thought we would start in French not to add one more layer of complexity but we definitely want to open up this project and this of a general international meta-ontology / standard. I you are interested I can share this interest at the next meeting 22nd Feb. The purpose is to enable a producer who manages his product catalog in one platform to open it to another platform with read/write rights (so that the product can be ordered from another platform and stock is modified accordingly). Also we imagine that if we manage to agree on a standard way to present products and transactions, we can imagine mutualized logistics services to happen...
I won't be at FOSDEM unfortunately :-(
Cheers

**Comment by djodjoni** [comment]
@enricostano welcome to Bxl :) I will give a you call tomorrow
@elf-pavlik Nice! I am ok anytime for a call :)
@myriamboure I am definitely interested. In fact this matches quite closely to something we are trying to do also "to enable a producer who manages his product catalog in one platform to open it to another platform with read/write rights". We have thought of various options around that but we are more steering towards a distributed solution where write rights are not needed rather enabling linked and discoverable data which can be copied. I can go in much more details but i don't think here is the right place. What is this meeting 22nd Feb you are mentioning? Is it something public?

**Comment by enricostano** [comment]
Hi everybody,

I've been talking over the weekend with @djodjoni and we've been talking about our projects/ideas. I think that here in Spain/Catalunya we're more focused on consumer groups than in producers selling directly their products. But I already see space of collaboration.

@myriamboure we've been looking at OFN project and we would like to have more info. Would be nice to have a video call. We're also interested in the 22nd Feb meeting, would be nice to join if it's public.

We'll have a meeting within our community of producers and consumer groups on 11th March to think about the opportunity of creating a platform coop that offers a SaaS here in Spain/Catalunya. Would be great to understand if/how we can contribute to OFN at technical level.

I hope we can meet ASAP since this kind of decisions will affect our roadmap of course. We're planning a crowdfunding campaign before the summer...

See you soon and thanks everybody!

**Comment by paroga** [comment]
In Austria we are in the process of setting up a (central) SaaS for the various foodcoops. We also want to share more data (e.g. article database) in the future across foodcoops, but don't have a exact plan for that at the moment. IMHO this overlaps to some extend with other projects (e.g. OFN).
I would be very interested in plans/ideas of the other projects, but must say that i do not know the exact use-case/workflow of the different projects. Does anybody know what's the same and what's different between them already?

**Comment by myriamboure** [comment]
@enricostano happy to plan a video call to discuss all that. End of week possible for me, tomorrow after 16:00, thrusday after 15:00 or Friday. If other want to join I see no issue if that's fine with you Enrico. 
Here is already a first video presentation of the functionnality: https://openfoodnetwork.org/user-guide/ and we have listed the functionnalities here: https://community.openfoodnetwork.org/t/feature-list-and-comparative-review/787
@paroga maybe you'll also be interested in the Food Dashboard where some platforms shared about their features https://github.com/ouisharelabs/food-dashboard/issues/1

About the DataFoodConsortium meeting, as I told you we have started with the local French speaking platforms, the 22nd meeting is not public, it's a working sessions between th 5 French platforms. But I know that would make sense to open up the topic with other peers abroad, so I propose to discuss that in the next meeting . We are really just starting, it's our second discussion, and it is easier to start small and local to build a first MVP to iterate on (agile). I'm super careful about the "human dimension" of such projects, and I don't want to go to big to quick or it could kill the bird in the egg ;-) We have told from the beginning that we would broaden the working group as this standard discussion need to be driven at the whole ecosystem level. It's just a question of timing and agile process given the local circumstances ;-) But I'll talk about it, and let you know!
@djodjoni I think we are aligned, I'm not technical myself so maybe not explaining things so clearly :-)

**Comment by sseerrggii** [comment]
Hello @myriamboure ! I'm part of the coopdevs team with @enricostano
Do you have a demo access? I would like to test the use case for consumer cooperatives in OFN

**Comment by paroga** [comment]
I know about food-dashboard already, but I never saw any kind of implementation yet. The other thing what I see is the [growing list](https://github.com/foodcoops/foodsoft/wiki/Other-foodcoop-software) of different software doing very similar things. I know already about 4 projects only in Austria. IMHO it's very sad that people start with the same stuff again and again, which results then in 10 products doing it "OK" instead of 1 product doing "BRILLIANT". I'm completely aware that different cooperatives have a different workflow, but I still think that there more room for collaboration. I'd still be interested in the reasons we people start new projects instead of joining existing one. Is it the license, the used technology, bad written code or is it just not possible to find the existing software when searching for it?

**Comment by myriamboure** [comment]
@sseerrggii hello! I have asked the Australian team to get a demo access to their English speaking staging, if you speak/understand French I can give you an access to the French staging actually. Let me know :-)

**Comment by myriamboure** [comment]
I understand your concern @paroga and share it, I think reasons are multiple and as humans are humans, we can't prevent it. For example Cagette.net, OS software for CSA, rewrote their own software because he saw OFN but it was in Ruby and he didn't know Ruby. It can be competences, I think also ego (I want to do my thing), or also sometime lack of information... too many info sometimes kill the info ;) That's why I do believe in interoperability more than making all contributors converge toward just one tool. But of course we are happy if as many contributors as possible would like to join the OFN contributors team :-) Our vision is really to built an open source infrastructure for food distribution, it's not focused on a specific model but an be tweaked and adapted to any model :-) Cheers!

**Comment by sseerrggii** [comment]
Hi @myriamboure 
I don't understand French very well, but it may be enough just to see the functionalities in action :wink:

**Comment by myriamboure** [comment]
@sseerrggii Anyway lot's of things are still not translated in the back office ;)  You can create a first hub here: https://staging.openfoodfrance.fr/register follow the form, then you will receive a confirmation email, you need to validate it to be able to access your enterprise back office (you will have to create a personal account first, then create the hub entreprise, you are guided through it). Ping me when you are there, I need to manually give you an entreprise limite > 1 so that you can create other enterprises (the ones for producers, etc.) Then you'll be able to fully play with it, and we can plan a call so that I can guide you for any issue you have and answer all your questions :-) You also have the user guide: https://openfoodnetwork.org/user-guide/ . You can write me on myriam@openfoodfrance.org, so that we don't mess up the thread here :-)

**Comment by enricostano** [comment]
> @myriamboure happy to plan a video call to discuss all that. End of week possible for me, tomorrow after 16:00, thrusday after 15:00 or Friday. If other want to join I see no issue if that's fine with you Enrico.

@myriamboure Would be OK for you this friday during the morning? We can meet on https://appear.in/coopdevs or any other place. I'm OK if anybody want to join of course.

**Comment by myriamboure** [comment]
@enricostano Ok Friday 11:30? Happy to try appear.in, let's meet on your link :-)

**Comment by paroga** [comment]
If the meeting will be held in English, I'd like to join it too, if that's ok. 11:30 CET?

**Comment by myriamboure** [comment]
Yep @paroga it will be in English and 11:30 CET :-)

**Comment by djodjoni** [comment]
I would like to join too if there is room left :). Btw :+1:  for interoperability. diversity of software helps for better matching solution to a problem and also 'competition' helps 'competitors' improve, however diversity to some extent, as @myriamboure  said: too much === nothing

**Comment by paroga** [comment]
I have nothing against diversity and I completely agree that different problems need different solutions. That's a reason why am very interested in how the other software works and for which use-case it was built.

Where I don't agree is that "competition helps competitors": Since we don't provide commercial closed-source products, there is no real market competition and urge to implement features for "customers" to get their money. This results in software where software 1 implements feature A and software 2 implements feature B+C. Developers of 1 may never need feature B+C, but a user of 1 would be highly interested in C, but also needs A. Developers of 2 don't see a need for A, which results that the user without programming skills has bad luck.

But anyway, I don't want to be negative! If people decide to start new projects that's completely their decision, but I'm just interested about the reasons and how their software works different. So maybe to get some inspiration for foodsoft. ;-)

**Comment by djodjoni** [comment]
by mentioning 'competition' here i mean the "personal ego" of the creator striving for better and practical software, but in no means real competition of course :) This happens a lot in opensourse  that people borrow code and ideas and it is great. As reargards to A,B and C first I see only the users of a need of features, developers just develop :) and in most of our cases we developers are also the users :) However more importantly all the pieces A,B,C etc can be made of different software using different language and running on different machines but if those can communicate and be connected together then we all win :) 
Btw i am also super interested to compare features and the logic and reasoning behind of those software because they are caused by actual need and aim to improve certain process. And this is not only for software inspiration but also helpful purely for organazing more practical food cycle.

Speaking about features and reasoning @paroga  do you have any documentation related to that for foodsoft, any kind from very general to highly technical?

**Comment by paroga** [comment]
Unfortunately developers are only a small part of the users. At least here in Austria a know a bunch of foodcoops where knowbody has the required knowledge for running the software. Thats the reason why we starting a SaaS for them, so they can benefit form fitting software too.

But that's only one point. Where i 100% agree is that we should make the connection between the different products possible. And it would be great if we could share our different workflows to "learn from each other" as you said already.

There exists a [nice video](https://vimeo.com/145927538) and a longer [user documentation](https://gaset.tetaneutral.net/doc/index.html), but they do not cover the "more advanced features". More information is available at the [wiki](https://github.com/foodcoops/foodsoft/wiki).

**Comment by myriamboure** [comment]
@sseerrggii I can create you a demo account on the Australian staging server now, but I need your email! Send it to me at myriam@openfoodfrance.org :-) Cheers

**Comment by sseerrggii** [comment]
@myriamboure I sent you an email ;)

**Comment by enricostano** [comment]
I opened a thread on OFN's community forum to keep talking about this:
https://community.openfoodnetwork.org/t/possible-ofn-instance-for-spain/809

Thanks everybody for all the inputs! We really enjoyed the meeting today 💪 :smiley

**Comment by enricostano** [comment]
Closing this since it seems that we're already connected and on the same page 💪 

Thanks everybody and see you soon!
