### ISSUE TITLE
Upgrade Rails to 6.x

### ISSUE THREAD

**Issue by t3k4y** [foodcoops/foodsoft#956]
Foodsoft urgently needs an Rails upgrade since 5.2 is not supported anymore.
(see https://endoflife.date/rails )
Rails 6 will end soon so it will be only an intermediate step.

See also issue on ruby-version: https://github.com/foodcoops/foodsoft/issues/939

**Comment by t3k4y** [comment]
In context of our project  for further developing foodsoft ( https://prototypefund.de/project/weiterentwicklung-von-foodsoft/ ) we are currently working on an pull request solving this issue.

Best wishes, T.

**Comment by paroga** [comment]
100% agree. i did the update from [4 to 5](https://github.com/foodcoops/foodsoft/commit/2557645f4fa223ba6ea562df0443199b73824f20), but there were a lot of incompatibilities, which need (a) code changes and (b) **extensive** manual testing (since the test coverage is not super high). I'm looking forward to merging the tests from the [yksflip fork](https://github.com/yksflip/foodsoft/tree/8_increase_test_coverage) into `master`.

IMHO we should "directly" upgrade to the most recent rails version (similar to my [4.2 to 5.2 upgrade](https://github.com/foodcoops/foodsoft/compare/2892d5272d6d564b1c8fd80acaa59aa291816d96...899a83bec424864e6bbe4ffb38ee1d210d013912) commits)

Do you have people who are willing to do the manual testing?

**Comment by t3k4y** [comment]
Hi paroga, 
thank you for your superfast reply! 

We are currently working on an upgrade to Rails 7.x
It seems pretty straight forward except the apivore incompatibility mentioned in https://github.com/foodcoops/foodsoft/issues/939#issuecomment-1099907198
Our approach is to rewrite the specs and swagger-file using the rswag-gem ( https://github.com/rswag/rswag ) 

In the next days @yksflip will start a pull request with the test code we have written to raise the coverage making the upgrade a little more save.

We are working together with a foodcoop willing to do manual testing in the field. 

Best wishes,
T.

**Comment by Viehlieb** [comment]
Hey folks,
The Upgrade to rails 6.1 looked good and as @t3k4y mentioned, we are directly head to 7.0 and ruby 2.7.2.
Currently we are facing issues with the

gem 'twitter-bootstrap-rails'

This gem supports rails 7, but comes with bootstrap 3, which makes code changes necessary anyways (for instance navbar and modal changed behavior). 

What do you think about using a different gem and go to bootstrap 5 straight away?
Drawback would be a different way of including the bootstrap framework due to asset pipeline changes ( as part of rails upgrade).

regards
viehlieb

**Comment by paroga** [comment]
I'd choose whatever gem is the most compatible and requires the least code changes. IMO you could choose whatever you think fits the most and you feel comfortable with, if you can ensure that it does not break anything of the existing code and you adopt the code of the whole repository to the new gem.

PS: If you have already a working 6.1 version, it would be great to create **separate** pull request for the update to 6.0 and 6.1, so we can review them already. There are probably some code changes like 3ffdb424d534b36d40c237e63cef8faaf67d6a81 or the switch to `rswag`, which can be integrated even before updating to a newer rails version.

**Comment by kidhab** [comment]
How can we support this tasks?

There are two merge requests connected to this task: #970 and #972.

The group working on improving thet Foodsoft already did an version [upgrade](https://git.local-it.org/Foodsoft/foodsoft/commit/fb8ccfea4a16c118deadfb8bdc0b22600b1ec859) for Ruby and Rails in their own repository.

**Comment by yksflip** [comment]
this would be my proposed steps to get the upgrade done: 

1. [ ]  controller tests #970 #972 
2. [ ]  rswag api tests #969 
3. [ ]  ruby, rails  [upgrade](https://git.local-it.org/Foodsoft/foodsoft/commit/fb8ccfea4a16c118deadfb8bdc0b22600b1ec859)
4. [ ]  [javacript importmaps](https://git.local-it.org/Foodsoft/foodsoft/src/branch/9_rails_v_7_js_importmap)

Until these changes are merged we maintain a [develop](https://git.local-it.org/Foodsoft/foodsoft/src/branch/develop)  branch with the mentioned changes and use it as a base for further feature developments. We test all this merged together in this [demo](https://git.local-it.org/Foodsoft/foodsoft/src/branch/demo) branch.

Happy to chat about any ideas how we could get some more traction on this whole thing :)

One more big todo is a bootstrap upgrade (v2 -> v5)
